### PR TITLE
CSS changes to be more like OWI website

### PR DESCRIPTION
**Pull request by mwernimont**
@wdwatkins @lindsaycarr So I did some changes to the theme to make it look more like the Website, which I think it does. But if you guys have other things you want changed or added let me know. Also I'm pretty sure I checked in everything I needed to, but let me know also if you aren't seeing any changes.

### CODE REVIEW

**Comment by jread-usgs** [comment]
any way I can take a look at this?

**Comment by ldecicco-USGS** [comment]
What's stopping you @jread-usgs ?

**Comment by lindsaycarr** [comment]
I like it - OWI-ified !!

**Comment by ldecicco-USGS** [comment]
Is there a new theme now? Because:
```
hugo server --theme=hugo_theme_robust --buildDrafts
```
looks a bit silly (the OWI is HUUUGGGEEEE)

**Comment by lindsaycarr** [comment]
hmmm doesn't look huge on mine
image

**Comment by ldecicco-USGS** [comment]
Is that the same command you used? ie:

```
hugo server --theme=hugo_theme_robust --buildDrafts
 ```

**Comment by ldecicco-USGS** [comment]
I restarted, and now looks normal

**Comment by lindsaycarr** [comment]
Yeah, using the same command. I wonder why it was doing that

**Comment by mwernimont** [comment]
CSS Wasn't being adhered probably. But def wouldn't leave the logo that huge. haha

**Pull request merged**
